use std::path::Path;

use anyhow::Result;
use specta::ts::{export, BigIntExportBehavior, ExportConfiguration};

use crate::types::{
    ApiResponse, ChatKind, ChatSummary, Config, DeepseekDiagnostics, DeepseekEndpointStatus,
    ErrorPayload, ListenTarget, Platform, RuntimeState, Status, Suggestion, SuggestionStyle,
    SuggestionsUpdated, UiPathStep, UiTreeExport, UiTreeLearnResult,
};

fn export_types() -> Result<String> {
    let config = ExportConfiguration::default().bigint(BigIntExportBehavior::Number);
    let mut output = String::new();

    output.push_str(&export::<RuntimeState>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<SuggestionStyle>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<Platform>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<ChatKind>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<ListenTarget>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<ChatSummary>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<Suggestion>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<Status>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<Config>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<UiTreeExport>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<UiPathStep>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<UiTreeLearnResult>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<SuggestionsUpdated>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<ErrorPayload>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<DeepseekEndpointStatus>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<DeepseekDiagnostics>(&config)?);
    output.push_str("\n\n");
    output.push_str(&export::<ApiResponse<()>>(&config)?);
    output.push_str("\n\n");

    Ok(output)
}

pub fn export_typescript_bindings(path: &Path) -> Result<()> {
    let mut output = String::new();
    output.push_str("// This file is auto-generated by src-tauri/src/bin/generate_bindings.rs.\n");
    output.push_str("// Do not edit this file directly.\n\n");
    output.push_str("import { invoke } from \"@tauri-apps/api/core\";\n\n");
    output.push_str(&export_types()?);
    output.push_str("export const commands = {\n");
    output.push_str("  getConfig: (): Promise<ApiResponse<Config>> => invoke(\"get_config\"),\n");
    output.push_str(
        "  setConfig: (config: Config): Promise<ApiResponse<null>> => invoke(\"set_config\", { config }),\n",
    );
    output.push_str(
        "  getStatus: (): Promise<ApiResponse<Status>> => invoke(\"get_status\"),\n",
    );
    output.push_str(
        "  getListenTargets: (): Promise<ApiResponse<ListenTarget[]>> => invoke(\"get_listen_targets\"),\n",
    );
    output.push_str(
        "  setListenTargets: (targets: ListenTarget[]): Promise<ApiResponse<null>> =>\n",
    );
    output.push_str(
        "    invoke(\"set_listen_targets\", { targets }),\n",
    );
    output.push_str(
        "  startListening: (): Promise<ApiResponse<null>> => invoke(\"start_listening\"),\n",
    );
    output.push_str("  stopListening: (): Promise<ApiResponse<null>> => invoke(\"stop_listening\"),\n");
    output.push_str(
        "  pauseListening: (): Promise<ApiResponse<null>> => invoke(\"pause_listening\"),\n",
    );
    output.push_str(
        "  resumeListening: (): Promise<ApiResponse<null>> => invoke(\"resume_listening\"),\n",
    );
    output.push_str(
        "  writeSuggestion: (chatId: string, text: string): Promise<ApiResponse<null>> =>\n",
    );
    output.push_str(
        "    invoke(\"write_suggestion\", { chat_id: chatId, text }),\n",
    );
    output.push_str(
        "  saveApiKey: (apiKey: string): Promise<ApiResponse<null>> => invoke(\"save_api_key\", { apiKey }),\n",
    );
    output.push_str(
        "  getApiKeyStatus: (): Promise<ApiResponse<boolean>> => invoke(\"get_api_key_status\"),\n",
    );
    output.push_str("  getApiKey: (): Promise<ApiResponse<string>> => invoke(\"get_api_key\"),\n");
    output.push_str("  deleteApiKey: (): Promise<ApiResponse<null>> => invoke(\"delete_api_key\"),\n");
    output.push_str(
        "  diagnoseDeepseek: (apiKey?: string): Promise<ApiResponse<DeepseekDiagnostics>> =>\n",
    );
    output.push_str(
        "    invoke(\"diagnose_deepseek\", apiKey ? { apiKey } : {}),\n",
    );
    output.push_str(
        "  listModels: (): Promise<ApiResponse<string[]>> => invoke(\"list_models\"),\n",
    );
    output.push_str(
        "  listRecentChats: (): Promise<ApiResponse<ChatSummary[]>> => invoke(\"list_recent_chats\"),\n",
    );
    output.push_str(
        "  exportWeChatUiTree: (maxDepth?: number, outputPath?: string): Promise<ApiResponse<UiTreeExport>> =>\n",
    );
    output.push_str(
        "    invoke(\"export_wechat_ui_tree\", { maxDepth, outputPath }),\n",
    );
    output.push_str(
        "  learnWeChatUiPaths: (maxDepth?: number, outputPath?: string): Promise<ApiResponse<UiTreeLearnResult>> =>\n",
    );
    output.push_str(
        "    invoke(\"learn_wechat_ui_paths\", { maxDepth, outputPath }),\n",
    );
    output.push_str(
        "  setDeepseekModel: (model: string): Promise<ApiResponse<null>> =>\n",
    );
    output.push_str("    invoke(\"set_deepseek_model\", { model }),\n");
    output.push_str("};\n");

    std::fs::write(path, output)?;
    Ok(())
}
