// This file is auto-generated by src-tauri/src/bin/generate_bindings.rs.
// Do not edit this file directly.

import { invoke } from "@tauri-apps/api/core";

export type RuntimeState = "idle" | "listening" | "generating" | "paused" | "error"

export type SuggestionStyle = "formal" | "neutral" | "casual"

export type Platform = "windows" | "macos" | "unknown"

export type ChatKind = "direct" | "group" | "unknown"

export type ListenTarget = { name: string; kind: ChatKind }

export type ChatSummary = { chat_id: string; chat_title: string; kind: ChatKind }

export type Suggestion = { id: string; style: SuggestionStyle; text: string }

export type Status = { state: RuntimeState; platform: Platform; agent_connected: boolean; last_error: string }

export type Config = { deepseek_model: string; suggestion_count: number; context_max_messages: number; context_max_chars: number; poll_interval_ms: number; listen_targets: { name: string; kind: ChatKind }[]; temperature: number; top_p: number; base_url: string; timeout_ms: number; max_retries: number; log_level: string; log_to_file: boolean }

export type UiTreeExport = { json: string; saved_to: string | null }

export type SuggestionsUpdated = { chat_id: string; suggestions: { id: string; style: SuggestionStyle; text: string }[] }

export type ErrorPayload = { code: string; message: string; recoverable: boolean }

export type DeepseekEndpointStatus = { ok: boolean; status: number | null; message: string }

export type DeepseekDiagnostics = { base_url: string; model: string; chat: { ok: boolean; status: number | null; message: string }; models: { ok: boolean; status: number | null; message: string } }

export type ApiResponse<T> = { success: boolean; message: string; data: T | null }

export const commands = {
  getConfig: (): Promise<ApiResponse<Config>> => invoke("get_config"),
  setConfig: (config: Config): Promise<ApiResponse<null>> => invoke("set_config", { config }),
  getStatus: (): Promise<ApiResponse<Status>> => invoke("get_status"),
  getListenTargets: (): Promise<ApiResponse<ListenTarget[]>> => invoke("get_listen_targets"),
  setListenTargets: (targets: ListenTarget[]): Promise<ApiResponse<null>> =>
    invoke("set_listen_targets", { targets }),
  startListening: (): Promise<ApiResponse<null>> => invoke("start_listening"),
  stopListening: (): Promise<ApiResponse<null>> => invoke("stop_listening"),
  pauseListening: (): Promise<ApiResponse<null>> => invoke("pause_listening"),
  resumeListening: (): Promise<ApiResponse<null>> => invoke("resume_listening"),
  writeSuggestion: (chatId: string, text: string): Promise<ApiResponse<null>> =>
    invoke("write_suggestion", { chat_id: chatId, text }),
  saveApiKey: (apiKey: string): Promise<ApiResponse<null>> => invoke("save_api_key", { apiKey }),
  getApiKeyStatus: (): Promise<ApiResponse<boolean>> => invoke("get_api_key_status"),
  getApiKey: (): Promise<ApiResponse<string>> => invoke("get_api_key"),
  deleteApiKey: (): Promise<ApiResponse<null>> => invoke("delete_api_key"),
  diagnoseDeepseek: (apiKey?: string): Promise<ApiResponse<DeepseekDiagnostics>> =>
    invoke("diagnose_deepseek", apiKey ? { apiKey } : {}),
  listModels: (): Promise<ApiResponse<string[]>> => invoke("list_models"),
  listRecentChats: (): Promise<ApiResponse<ChatSummary[]>> => invoke("list_recent_chats"),
  exportWeChatUiTree: (maxDepth?: number, outputPath?: string): Promise<ApiResponse<UiTreeExport>> =>
    invoke("export_wechat_ui_tree", { maxDepth, outputPath }),
  setDeepseekModel: (model: string): Promise<ApiResponse<null>> =>
    invoke("set_deepseek_model", { model }),
};
